import { EavAttributeDTO, EavAttributeStatus, EavAttributeTypes } from '@cbidigital/aqua';
import { Logger, OnStart, Service } from '@cbidigital/heron-common';
import { Inject } from '@heronjs/common';
import {
    IProfileDAO,
    IProfileAttributeDAO,
} from '@cbidigital/profile-module/features/profile/infra/databases';
import { ProfileTokens } from '@cbidigital/profile-module/constants';
import { ProfileCommonAttributesDto, ProfileLaityAttributesDto, ProfilePriestAttributesDto } from '../../domain/dtos';

type attributesDto = ProfileCommonAttributesDto & ProfileLaityAttributesDto & ProfilePriestAttributesDto;
type a = 'h' | 'a'
@Service()
export class ProfileSeedService {
    private _logger: Logger;

    constructor(
        @Inject(ProfileTokens.Dao.PROFILE)
        private readonly _profileDao: IProfileDAO,
        @Inject(ProfileTokens.Dao.PROFILE_ATTRIBUTE)
        private readonly _profileAttributeDao: IProfileAttributeDAO,
    ) {
        this._logger = new Logger(ProfileSeedService.name);
    }

    @OnStart()
    async runSeeds() {
        // Create profile attributes
        (async () => {
            const profileAttrDTOs: (EavAttributeDTO & { code: keyof attributesDto })[] = [
                {
                    code: 'holyNameCode',
                    label: 'Mã tên thánh',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'positionId',
                    label: 'ID vị trí phục vụ',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'societyNameCode',
                    label: 'Mã tên dòng',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'isStudyingAbroad',
                    label: 'Đang du học',
                    systemDefined: true,
                    type: EavAttributeTypes.BOOLEAN,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'nationality',
                    label: 'Quốc Tịch',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'dod',
                    label: 'Ngày Mất',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'ordainedDate',
                    label: 'Ngày thụ phong',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'ordainedDepartmentId',
                    label: 'ID nơi thụ phong giáo phận',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'celebratingPriest',
                    label: 'Người cử hành',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'celebratingPriestHolyNameCode',
                    label: 'Tên Thánh Người cử hành',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'oldPositionEndDate',
                    label: 'Ngày kết thúc mục vụ cũ',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'newPositionStartDate',
                    label: 'Ngày bắt đầu mục vụ mới',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'positionGroupCode',
                    label: 'Nhóm vị trí phục vụ',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'fullName',
                    label: 'Họ và Tên',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'placeOfBirth',
                    label: 'Nơi Sinh',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'fatherHolyNameCode',
                    label: 'Tên Thánh Của Cha',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'fatherName',
                    label: 'Họ Và Tên Cha',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'motherHolyNameCode',
                    label: 'Tên Thánh Của Mẹ',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'motherName',
                    label: 'Họ Và Tên Mẹ',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'dateOfBaptism',
                    label: 'Ngày Rửa Tội',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'placeOfBaptism',
                    label: 'Nơi Rửa Tội',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'baptizedBy',
                    label: 'Người Rửa Tội',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'baptizedByHolyNameCode',
                    label: 'Tên Thánh Người Rửa Tội',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'baptismalGodParent',
                    label: 'Người Đỡ Đầu Rửa Tội',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'baptismalGodParentHolyNameCode',
                    label: 'Tên Thánh Người Đỡ Đầu Rửa Tội',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'dateOfFirstCommunion',
                    label: 'Ngày Rước Lễ Lần Đầu',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'placeOfFirstCommunion',
                    label: 'Nơi Rước Lễ Lần Đầu',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'dateOfComfirmation',
                    label: 'Ngày Thêm Sức',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'confirmationBookOrderNo',
                    label: 'Số Thứ Tự Sổ Thêm Sức',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'placeOfConfirmation',
                    label: 'Nơi Thêm Sức',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'confirmationAdministeredBy',
                    label: 'Người Cho Thêm Sức',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'confirmationAdministeredByHolyNameCode',
                    label: 'Tên Thánh Người Cho Thêm Sức',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'confirmationGodParent',
                    label: 'Người Đỡ Đầu Thêm Sức',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'confirmationGodParentHolyNameCode',
                    label: 'Tên Thánh Người Đỡ Đầu Thêm Sức',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'dateOfMarriage',
                    label: 'Ngày Hôn Phối',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'marriageCertificateOrderNo',
                    label: 'Số Thứ Tự Sổ Hôn Phối',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'placeOfMarriage',
                    label: 'Nơi Cử Hành',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'marriedWith',
                    label: 'Kết Hôn Với',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'marriedWithHolyNameCode',
                    label: 'Tên Thánh Kết Hôn Với',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'weddingCelebratedBy',
                    label: 'Người Cử Hành Hôn Phối',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'weddingCelebratedByHolyNameCode',
                    label: 'Người Cử Hành Hôn Phối',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'witness1',
                    label: 'Người Chứng I',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'witness1HolyNameCode',
                    label: 'Tên Thánh Người Chứng I',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'witness2',
                    label: 'Người Chứng II',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'witness2HolyNameCode',
                    label: 'Tên Thánh Người Chứng II',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'note',
                    label: 'Ghi Chú',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'dataEntriedBy',
                    label: 'Người Nhập Liệu',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'dateOfDataEntry',
                    label: 'Ngày Nhập Liệu',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'lastUpdatedBy',
                    label: 'Người Cập Nhật Cuối',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
                {
                    code: 'lastUpdatedAt',
                    label: 'Ngày Cập Nhật Cuối',
                    systemDefined: true,
                    type: EavAttributeTypes.STRING,
                    visibility: true,
                    status: EavAttributeStatus.ENABLED,
                    sortOrder: 0,
                    isRequired: false,
                    editable: true,
                    createdAt: new Date(),
                    updatedAt: null,
                    options: [],
                },
            ];

            const profileAttributesExist = await this._profileAttributeDao.find({
                filter: {
                    code: { in: profileAttrDTOs.map((item) => item.code) },
                },
            });

            const profileAttributesNeedToCreate = profileAttrDTOs.filter(
                (p) => !profileAttributesExist.find((item) => item.code === p.code),
            );

            if (profileAttributesNeedToCreate.length) {
                await this._profileAttributeDao.createList(profileAttributesNeedToCreate);
                this._logger.info('Run seeds: Profile attributes created');
            }
        })();
    }
}
